name: ship go-aws to docker hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u devblinchik
    - name: Build the Docker image
      run: docker build -t devblinchik/go-aws:latest .
    - name: push go-aws to docker hub 
      run: docker push devblinchik/go-aws:latest
    - name: docker logout
      run: docker logout
